export const ROUTE_CHECK_PAGE = String.raw`<!doctype html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="color-scheme" content="dark">
  <title>Saturn Workspace | Connection route check</title>
  <style>
    :root{font-family:"Segoe UI",Tahoma,sans-serif;color:#f5f7ff;background:#080b14}
    *{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;padding:24px;background:radial-gradient(circle at 70% 15%,#283263 0,transparent 36%),linear-gradient(145deg,#090d18,#111629)}
    main{width:min(680px,100%);border:1px solid #313b68;border-radius:28px;padding:34px;background:rgba(15,20,38,.92);box-shadow:0 24px 80px #0008}
    header{display:flex;align-items:center;gap:14px}.mark{width:44px;height:44px;border-radius:15px;display:grid;place-items:center;background:linear-gradient(135deg,#8b7cff,#4ce0c1);color:#090d18;font-weight:900;font-size:24px}
    h1{font-size:clamp(24px,5vw,38px);margin:22px 0 10px;line-height:1.2}p{color:#bbc2db;line-height:1.8;margin:0}
    .status{margin:28px 0;padding:20px;border-radius:18px;background:#111830;border:1px solid #29345f;display:flex;gap:15px;align-items:center}
    .orb{width:18px;height:18px;border-radius:50%;background:#f6c25c;box-shadow:0 0 0 7px #f6c25c22;animation:pulse 1.2s ease-in-out infinite}
    .status.ok .orb{background:#4ce0a5;box-shadow:0 0 0 7px #4ce0a522;animation:none}.status.bad .orb{background:#ff6b7e;box-shadow:0 0 0 7px #ff6b7e22;animation:none}
    .status strong{display:block;margin-bottom:4px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.item{padding:15px;border-radius:14px;background:#0b1020;border:1px solid #222c50}.item:last-child{grid-column:1/-1}.item span{display:block;color:#8f99ba;font-size:13px;margin-bottom:7px}.item b{font-size:15px}
    footer{margin-top:24px;padding-top:20px;border-top:1px solid #252e50;color:#8f99ba;font-size:13px;line-height:1.7}@keyframes pulse{50%{opacity:.45;transform:scale(.82)}}
    @media(max-width:520px){main{padding:24px}.grid{grid-template-columns:1fr}}
    @media(prefers-reduced-motion:reduce){.orb{animation:none}}
  </style>
</head>
<body>
<main>
  <header><div class="mark">S</div><strong>Saturn Workspace</strong></header>
  <h1 id="heading"></h1>
  <p id="intro"></p>
  <section class="status" id="status" aria-live="polite"><i class="orb" aria-hidden="true"></i><div><strong id="title"></strong><span id="detail"></span></div></section>
  <section class="grid" id="results">
    <div class="item"><span id="https-label"></span><b id="https"></b></div>
    <div class="item"><span id="dns-label"></span><b id="dns"></b></div>
    <div class="item"><span>IPv4</span><b id="ipv4"></b></div>
    <div class="item"><span>IPv6</span><b id="ipv6"></b></div>
    <div class="item"><span>WebRTC</span><b id="webrtc"></b></div>
    <div class="item"><span id="exit-label"></span><b id="exit"></b></div>
    <div class="item"><span id="result-label"></span><b id="result"></b></div>
  </section>
  <footer id="privacy"></footer>
</main>
<script>
const isArabic=(navigator.language||'').toLowerCase().startsWith('ar');
const copies={
  en:{heading:'Connection route check',intro:'Saturn is verifying that this browser environment uses the connection route you selected before it opens your links. This check does not send your Saturn identity, browsing links, or proxy credentials.',checking:'Checking…',waitingDetail:'Session links will stay closed until the check finishes.',results:'Connection check results',secure:'Encrypted connection',dnsLabel:'Measurement page name reached',pending:'Checking',exitLabel:'Exit address',masked:'Not shown in full',resultLabel:'Result',waiting:'Waiting',qualified:'Route qualified',unqualified:'Route not qualified',invalidTitle:'Could not start the check',invalidDetail:'The attempt token is invalid. Return to Saturn and try again.',proved:'Route proved',unavailable:'Unavailable or unconfirmed',dnsLimited:'Name reached; DNS resolver route was not measured',sideDetected:'A side route was detected and is being verified',noSide:'No visible unrelayed side route',unknown:'Unconfirmed',connected:'Connected',measured:'Measured',measurementDone:'Measurement complete',verifying:'Saturn is verifying the result before it opens the session links.',successTitle:'Route qualified',failureTitle:'Route not qualified',successDetail:'The environment is qualified. Session links will open shortly.',failureDetail:'Saturn detected a leak or an unconfirmed route, so session links will not open.',ackFailed:'The result is visible, but the app could not confirm that it was rendered. The operation will fail closed.',failed:'Failed',failedTitle:'Could not complete the check',failedDetail:'The environment was not declared successful. Close this page and review the result in Saturn.',privacy:'This attempt-only check contacts Saturn route endpoints and Cloudflare STUN infrastructure to detect WebRTC side routes. Results are removed within minutes, and Saturn does not monitor later browsing.'},
  ar:{heading:'فحص مسار الاتصال',intro:'تتحقق Saturn من أن بيئة المتصفح تستخدم مسار الاتصال الذي اخترته قبل فتح روابطك. لا يرسل هذا الفحص هوية حسابك في Saturn أو روابط التصفح أو بيانات اعتماد البروكسي.',checking:'جارٍ التحقق…',waitingDetail:'لن تُفتح روابط الجلسة قبل اكتمال الفحص.',results:'نتائج فحص الاتصال',secure:'الاتصال المشفّر',dnsLabel:'الوصول إلى اسم صفحة القياس',pending:'جارٍ الفحص',exitLabel:'عنوان الخروج',masked:'لا يُعرض كاملًا',resultLabel:'النتيجة',waiting:'قيد الانتظار',qualified:'المسار مؤهل',unqualified:'المسار غير مؤهل',invalidTitle:'تعذر بدء الفحص',invalidDetail:'رمز المحاولة غير صالح. ارجع إلى Saturn وأعد المحاولة.',proved:'تم إثبات المسار',unavailable:'غير متاح أو غير مؤكد',dnsLimited:'تم الوصول إلى الاسم؛ مسار محلل DNS غير مقاس',sideDetected:'اكتُشف مسار جانبي ويجري التحقق منه',noSide:'لا يوجد مسار جانبي غير مرحّل ظاهر',unknown:'نتيجة غير مؤكدة',connected:'متصل',measured:'تم القياس',measurementDone:'اكتمل القياس',verifying:'تتحقق Saturn الآن من النتيجة قبل فتح روابط الجلسة.',successTitle:'المسار مؤهل',failureTitle:'المسار غير مؤهل',successDetail:'تم تأهيل البيئة، وستفتح روابط الجلسة بعد لحظات.',failureDetail:'اكتشفت Saturn تسربًا أو مسارًا غير مؤكد، لذلك لن تفتح روابط الجلسة.',ackFailed:'ظهرت النتيجة، لكن تعذر تأكيد عرضها للتطبيق؛ ستفشل العملية بصورة مغلقة.',failed:'فشل',failedTitle:'تعذر إكمال الفحص',failedDetail:'لم نعلن نجاح البيئة. أغلق هذه الصفحة وراجع النتيجة داخل Saturn.',privacy:'يتصل هذا الفحص الخاص بالمحاولة بنقاط قياس Saturn وبنية STUN التابعة لـCloudflare لاكتشاف مسارات WebRTC الجانبية. تُحذف النتائج خلال دقائق ولا تراقب Saturn التصفح اللاحق.'}
};
const c=isArabic?copies.ar:copies.en;document.documentElement.lang=isArabic?'ar':'en';document.documentElement.dir=isArabic?'rtl':'ltr';document.title='Saturn Workspace | '+c.heading;
const byId=(id)=>document.getElementById(id);const status=byId('status');
byId('heading').textContent=c.heading;byId('intro').textContent=c.intro;byId('title').textContent=c.checking;byId('detail').textContent=c.waitingDetail;byId('results').setAttribute('aria-label',c.results);byId('https-label').textContent=c.secure;byId('dns-label').textContent=c.dnsLabel;byId('exit-label').textContent=c.exitLabel;byId('result-label').textContent=c.resultLabel;for(const id of ['https','dns','ipv4','ipv6','webrtc'])byId(id).textContent=c.pending;byId('exit').textContent=c.masked;byId('result').textContent=c.waiting;byId('privacy').textContent=c.privacy;
const q=new URLSearchParams(location.hash.slice(1));const attempt=q.get('attempt')||'';let token='';history.replaceState(null,'',location.pathname+location.search);
function finish(ok,title,detail){status.className='status '+(ok?'ok':'bad');byId('title').textContent=title;byId('detail').textContent=detail;byId('result').textContent=ok?c.qualified:c.unqualified}
function classify(candidate){const raw=String(candidate?.candidate||candidate||'').toLowerCase();const type=String(candidate?.type||'').toLowerCase();const relay=type==='relay'||/ typ relay /.test(raw);const address=String(candidate?.address||(raw.match(/candidate:\S+ \d+ \S+ \d+ ([^ ]+)/)||[])[1]||'').toLowerCase().replace(/^\[|\]$/g,'');const mdns=/\.local$/.test(address);const ipv4=/^(?:\d{1,3}\.){3}\d{1,3}$/.test(address);const ipv6=address.includes(':')&&/^[0-9a-f:]+$/.test(address);const privateIp=/^(10\.|192\.168\.|172\.(1[6-9]|2\d|3[01])\.|127\.|169\.254\.|::1$|f[cd][0-9a-f]{2}:|fe[89ab][0-9a-f]:)/i.test(address);return{address,relay,privateIp,publicIp:(ipv4||ipv6)&&!mdns&&!privateIp&&!relay}}
async function waitForIceGathering(pc,timeoutMs){if(pc.iceGatheringState==='complete')return true;return await new Promise(resolve=>{let settled=false;const finish=(value)=>{if(settled)return;settled=true;clearTimeout(timer);pc.removeEventListener('icegatheringstatechange',changed);resolve(value)};const changed=()=>{if(pc.iceGatheringState==='complete')finish(true)};const timer=setTimeout(()=>finish(false),timeoutMs);pc.addEventListener('icegatheringstatechange',changed)})}
async function probeWebRtc(){let pc;const pubs=new Set();let priv=false,relay=false;try{pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.cloudflare.com:3478'}]});pc.createDataChannel('route');pc.onicecandidate=(e)=>{if(!e.candidate)return;const candidate=classify(e.candidate);if(candidate.publicIp&&candidate.address)pubs.add(candidate.address);priv=priv||candidate.privateIp;relay=relay||candidate.relay};await pc.setLocalDescription(await pc.createOffer());const complete=await waitForIceGathering(pc,8000);const publicCandidates=[...pubs].slice(0,8);return{webrtc_public_candidate:publicCandidates.length>0,webrtc_public_candidates:publicCandidates,webrtc_private_candidate:priv,webrtc_relay_candidate:relay,webrtc_gathering_completed:complete,browser_probe_completed:complete}}catch{return{webrtc_public_candidate:false,webrtc_public_candidates:[],webrtc_private_candidate:false,webrtc_relay_candidate:false,webrtc_gathering_completed:false,browser_probe_completed:false}}finally{if(pc)pc.close()}}
async function probeNetwork(family){const local=/^(127\.0\.0\.1|localhost|\[::1\])$/.test(location.hostname);const endpoint=local?('/v1/network?family='+family):('https://'+(family==='ipv4'?'v4':'v6')+'.route-check.saturnws.com/v1/network');const headers={'Content-Type':'application/json','X-Route-Attempt':attempt,'X-Route-Token':token};if(local)headers['X-Saturn-QA-Loopback']='1';try{const response=await fetch(endpoint,{method:'POST',headers,body:'{}',cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer'});const data=await response.json();if(!response.ok||!data.success)throw new Error('network_probe_rejected');return data}catch{return null}}
async function waitDecision(){for(let i=0;i<40;i+=1){try{const response=await fetch('/v1/browser-result',{method:'POST',headers:{'Content-Type':'application/json','X-Route-Attempt':attempt,'X-Route-Token':token},body:'{}',cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer'});const data=await response.json();if(response.ok&&data.success&&data.decision)return data}catch{}await new Promise(resolve=>setTimeout(resolve,250))}return null}
async function acknowledgeDecision(){await new Promise(resolve=>requestAnimationFrame(()=>setTimeout(resolve,600)));try{const response=await fetch('/v1/browser-ack',{method:'POST',headers:{'Content-Type':'application/json','X-Route-Attempt':attempt,'X-Route-Token':token},body:'{}',cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer'});return response.ok}catch{return false}}
async function runCheck(){try{const [ipv4,ipv6,observation]=await Promise.all([probeNetwork('ipv4'),probeNetwork('ipv6'),probeWebRtc()]);observation.ipv4_probe_attempted=true;observation.ipv6_probe_attempted=true;byId('ipv4').textContent=ipv4?c.proved:c.unavailable;byId('ipv6').textContent=ipv6?c.proved:c.unavailable;byId('dns').textContent=c.dnsLimited;const sidePath=observation.webrtc_private_candidate||observation.webrtc_public_candidate;byId('webrtc').textContent=observation.browser_probe_completed?(sidePath?c.sideDetected:c.noSide):c.unknown;const response=await fetch('/v1/observe',{method:'POST',headers:{'Content-Type':'application/json','X-Route-Attempt':attempt,'X-Route-Token':token},body:JSON.stringify(observation),cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer'});const data=await response.json();if(!response.ok||!data.success)throw new Error('probe_rejected');byId('https').textContent=c.connected;byId('exit').textContent=data.exit_ip_masked||ipv4?.exit_ip_masked||ipv6?.exit_ip_masked||c.measured;byId('title').textContent=c.measurementDone;byId('detail').textContent=c.verifying;const decision=await waitDecision();if(!decision)throw new Error('decision_unavailable');const qualified=decision.decision==='qualified';finish(qualified,qualified?c.successTitle:c.failureTitle,qualified?c.successDetail:c.failureDetail);if(!await acknowledgeDecision())byId('detail').textContent=c.ackFailed}catch{byId('https').textContent=c.failed;for(const id of ['dns','ipv4','ipv6','webrtc'])byId(id).textContent=c.unknown;finish(false,c.failedTitle,c.failedDetail)}}
let started=false;window.__saturnStartRouteCheck=(input)=>{if(started||!input||input.attempt!==attempt||!/^[A-Za-z0-9_-]{32,64}$/.test(attempt)||typeof input.token!=='string'||input.token.length<32||input.token.length>256)return false;started=true;token=input.token;void runCheck();return true};setTimeout(()=>{if(!started)finish(false,c.invalidTitle,c.invalidDetail)},15000);
</script>
</body>
</html>`
