export const ROUTE_CHECK_PAGE = String.raw`<!doctype html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="color-scheme" content="light">
  <title>Saturn Workspace | Connection route check</title>
  <style>
    :root{color-scheme:light;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#171715;background:#f7f7f5}
    *{box-sizing:border-box}
    html{min-width:320px}body{margin:0;min-width:320px;min-height:100vh;border-block-start:4px solid #2474d2}
    html[lang="ar"] body{font-family:Tajawal,"Segoe UI",sans-serif}
    main{width:min(100% - 64px,940px);margin:0 auto;padding:34px 0 46px}
    header{display:flex;align-items:center;justify-content:space-between;gap:20px;padding-bottom:27px;border-bottom:1px solid #e3e3df}
    .brand{display:flex;align-items:center;gap:11px;font-size:15px;letter-spacing:-.02em}
    .mark{width:34px;height:34px;border-radius:10px;display:grid;place-items:center;background:#2474d2;color:#fff;font-weight:800;font-size:21px;line-height:1}
    .context{color:#5f5e59;font-size:12px;font-weight:650;letter-spacing:.07em;text-transform:uppercase}
    .hero{max-width:730px;margin:38px 0 28px}
    h1{margin:0 0 13px;font-size:clamp(29px,4vw,43px);font-weight:720;letter-spacing:-.045em;line-height:1.16}
    p{margin:0;color:#5f5e59;font-size:15px;line-height:1.65}
    .status{--status-accent:#2474d2;--status-surface:#edf5ff;display:flex;align-items:flex-start;gap:17px;padding:25px 26px;margin-bottom:31px;background:var(--status-surface);border-inline-start:4px solid var(--status-accent);border-radius:0 12px 12px 0}
    html[dir="rtl"] .status{border-radius:12px 0 0 12px}
    .status.ok{--status-accent:#1c7c54;--status-surface:#e9f6ef}.status.bad{--status-accent:#c73b4a;--status-surface:#fff0f2}
    .orb{flex:none;width:13px;height:13px;margin-top:7px;border-radius:50%;background:var(--status-accent);box-shadow:0 0 0 5px color-mix(in srgb,var(--status-accent) 14%,transparent);animation:pulse 1.6s ease-in-out infinite}
    .status.ok .orb,.status.bad .orb{animation:none}
    .status-copy{min-width:0}.status-kicker{display:block;color:var(--status-accent);font-size:12px;font-weight:750;letter-spacing:.055em;text-transform:uppercase}
    .status strong{display:block;margin:5px 0 4px;font-size:23px;line-height:1.3;letter-spacing:-.025em}#detail{display:block;color:#424641;font-size:14px;line-height:1.6}
    .evidence{display:grid;grid-template-columns:minmax(180px,.85fr) minmax(0,1.65fr);align-items:center;gap:24px;padding:0 0 29px;border-bottom:1px solid #e3e3df}
    .evidence-label{display:block;margin-bottom:6px;color:#5f5e59;font-size:13px;font-weight:650}
    .evidence-caption{display:block;color:#85837c;font-size:12px;line-height:1.5}
    .exit-value{display:block;max-width:100%;color:#171715;font:650 clamp(24px,3.4vw,37px)/1.25 ui-monospace,SFMono-Regular,Consolas,monospace;letter-spacing:-.045em;overflow-wrap:anywhere;user-select:text;unicode-bidi:isolate}
    .checks{margin-top:30px}.checks h2{margin:0 0 8px;font-size:18px;letter-spacing:-.025em}
    .checks-note{margin:0 0 17px;color:#85837c;font-size:13px}
    .check-list{margin:0;padding:0;border-block-start:1px solid #e3e3df}.check-row{display:grid;grid-template-columns:minmax(150px,1fr) minmax(0,2fr);gap:22px;align-items:baseline;padding:13px 0;border-block-end:1px solid #e3e3df}
    .check-row dt{color:#5f5e59;font-size:13px}.check-row dd{margin:0;color:#171715;font-size:14px;font-weight:650;line-height:1.5;overflow-wrap:anywhere}
    footer{margin-top:29px;color:#77756e;font-size:12px;line-height:1.7;max-width:760px}
    @keyframes pulse{50%{opacity:.52;transform:scale(.8)}}
    @media(max-width:600px){main{width:min(100% - 32px,940px);padding-top:22px}header{padding-bottom:20px}.context{font-size:10px;text-align:end}.hero{margin:31px 0 23px}.status{padding:20px;gap:14px;margin-bottom:28px}.status strong{font-size:21px}.evidence{grid-template-columns:1fr;gap:10px}.check-row{grid-template-columns:1fr;gap:3px;padding:12px 0}}
    @media(prefers-reduced-motion:reduce){.orb{animation:none}}
  </style>
</head>
<body>
<main>
  <header><div class="brand"><div class="mark" aria-hidden="true">S</div><strong>Saturn Workspace</strong></div><span class="context" id="context"></span></header>
  <div class="hero"><h1 id="heading"></h1><p id="intro"></p></div>
  <section class="status" id="status" aria-live="polite" aria-atomic="true"><i class="orb" aria-hidden="true"></i><div class="status-copy"><span class="status-kicker"><span id="result-label"></span> · <span id="result"></span></span><strong id="title"></strong><span id="detail"></span></div></section>
  <section class="evidence" aria-labelledby="exit-label"><div><span class="evidence-label" id="exit-label"></span><span class="evidence-caption" id="exit-note"></span></div><b class="exit-value" id="exit" dir="ltr"></b></section>
  <section class="checks" id="results" aria-labelledby="results-heading"><h2 id="results-heading"></h2><p class="checks-note" id="checks-note"></p><dl class="check-list">
    <div class="check-row"><dt id="https-label"></dt><dd id="https"></dd></div>
    <div class="check-row"><dt>IPv4</dt><dd id="ipv4"></dd></div>
    <div class="check-row"><dt>IPv6</dt><dd id="ipv6"></dd></div>
    <div class="check-row"><dt>WebRTC</dt><dd id="webrtc"></dd></div>
    <div class="check-row"><dt id="dns-label"></dt><dd id="dns"></dd></div>
  </dl></section>
  <footer id="privacy"></footer>
</main>
<script>
const isArabic=(navigator.language||'').toLowerCase().startsWith('ar');
const copies={
  en:{heading:'Connection route check',intro:'Saturn is verifying that this browser environment uses the connection route you selected before it opens your links. This check does not send your Saturn identity, browsing links, or proxy credentials.',checking:'Checking…',waitingDetail:'Session links will stay closed until the check finishes.',results:'Connection check results',secure:'Encrypted connection',dnsLabel:'Measurement page name reached',pending:'Checking',exitLabel:'Exit address',masked:'Not shown in full',resultLabel:'Result',waiting:'Waiting',qualified:'Route qualified',unqualified:'Route not qualified',invalidTitle:'Could not start the check',invalidDetail:'The attempt token is invalid. Return to Saturn and try again.',proved:'Route proved',unavailable:'Unavailable or unconfirmed',dnsLimited:'Name reached; DNS resolver route was not measured',sideDetected:'A side route was detected and is being verified',noSide:'No visible unrelayed side route',unknown:'Unconfirmed',connected:'Connected',measured:'Measured',measurementDone:'Measurement complete',verifying:'Saturn is verifying the result before it opens the session links.',successTitle:'Route qualified',failureTitle:'Route not qualified',successDetail:'The environment is qualified. Session links will open shortly.',failureDetail:'Saturn detected a leak or an unconfirmed route, so session links will not open.',ackFailed:'Saturn could not confirm this result with the browser. Session links will stay closed.',failed:'Failed',failedTitle:'Could not complete the check',failedDetail:'The environment was not declared successful. Close this page and review the result in Saturn.',privacy:'This attempt-only check contacts Saturn route endpoints and Cloudflare STUN infrastructure to detect WebRTC side routes. Results are removed within minutes, and Saturn does not monitor later browsing.'},
  ar:{heading:'فحص مسار الاتصال',intro:'تتحقق Saturn من أن بيئة المتصفح تستخدم مسار الاتصال الذي اخترته قبل فتح روابطك. لا يرسل هذا الفحص هوية حسابك في Saturn أو روابط التصفح أو بيانات اعتماد البروكسي.',checking:'جارٍ التحقق…',waitingDetail:'لن تُفتح روابط الجلسة قبل اكتمال الفحص.',results:'نتائج فحص الاتصال',secure:'الاتصال المشفّر',dnsLabel:'الوصول إلى اسم صفحة القياس',pending:'جارٍ الفحص',exitLabel:'عنوان الخروج',masked:'لا يُعرض كاملًا',resultLabel:'النتيجة',waiting:'قيد الانتظار',qualified:'المسار مؤهل',unqualified:'المسار غير مؤهل',invalidTitle:'تعذر بدء الفحص',invalidDetail:'رمز المحاولة غير صالح. ارجع إلى Saturn وأعد المحاولة.',proved:'تم إثبات المسار',unavailable:'غير متاح أو غير مؤكد',dnsLimited:'تم الوصول إلى الاسم؛ مسار محلل DNS غير مقاس',sideDetected:'اكتُشف مسار جانبي ويجري التحقق منه',noSide:'لا يوجد مسار جانبي غير مرحّل ظاهر',unknown:'نتيجة غير مؤكدة',connected:'متصل',measured:'تم القياس',measurementDone:'اكتمل القياس',verifying:'تتحقق Saturn الآن من النتيجة قبل فتح روابط الجلسة.',successTitle:'المسار مؤهل',failureTitle:'المسار غير مؤهل',successDetail:'تم تأهيل البيئة، وستفتح روابط الجلسة بعد لحظات.',failureDetail:'اكتشفت Saturn تسربًا أو مسارًا غير مؤكد، لذلك لن تفتح روابط الجلسة.',ackFailed:'تعذر تأكيد نتيجة الفحص بين المتصفح وSaturn؛ ستبقى روابط الجلسة مغلقة.',failed:'فشل',failedTitle:'تعذر إكمال الفحص',failedDetail:'لم نعلن نجاح البيئة. أغلق هذه الصفحة وراجع النتيجة داخل Saturn.',privacy:'يتصل هذا الفحص الخاص بالمحاولة بنقاط قياس Saturn وبنية STUN التابعة لـCloudflare لاكتشاف مسارات WebRTC الجانبية. تُحذف النتائج خلال دقائق ولا تراقب Saturn التصفح اللاحق.'}
};
const c=isArabic?copies.ar:copies.en;document.documentElement.lang=isArabic?'ar':'en';document.documentElement.dir=isArabic?'rtl':'ltr';document.title='Saturn Workspace | '+c.heading;
const visualCopy=isArabic?{context:'التحقق من الجلسة',exitNote:'عنوان الخروج المقاس لهذه المحاولة فقط',checksNote:'هذه النتائج تخص بدء الجلسة الحالي، وليست مراقبة مستمرة للتصفح.',secure:'اتصال صفحة القياس المشفّر',ackFailedTitle:'تعذر تأكيد الفحص'}:{context:'Session verification',exitNote:'Exit address measured for this attempt only',checksNote:'These results describe this session start, not ongoing browsing.',secure:'Encrypted measurement connection',ackFailedTitle:'Could not confirm the check'};
const byId=(id)=>document.getElementById(id);const status=byId('status');
byId('context').textContent=visualCopy.context;byId('heading').textContent=c.heading;byId('intro').textContent=c.intro;byId('title').textContent=c.checking;byId('detail').textContent=c.waitingDetail;byId('results-heading').textContent=c.results;byId('checks-note').textContent=visualCopy.checksNote;byId('https-label').textContent=visualCopy.secure;byId('dns-label').textContent=c.dnsLabel;byId('exit-label').textContent=c.exitLabel;byId('exit-note').textContent=visualCopy.exitNote;byId('result-label').textContent=c.resultLabel;for(const id of ['https','dns','ipv4','ipv6','webrtc'])byId(id).textContent=c.pending;byId('exit').textContent=c.pending;byId('result').textContent=c.waiting;byId('privacy').textContent=c.privacy;
const q=new URLSearchParams(location.hash.slice(1));const attempt=q.get('attempt')||'';const launchToken=q.get('token')||'';let token='';history.replaceState(null,'',location.pathname+location.search);
function finish(ok,title,detail){status.className='status '+(ok?'ok':'bad');byId('title').textContent=title;byId('detail').textContent=detail;byId('result').textContent=ok?c.qualified:c.unqualified}
function classify(candidate){const raw=String(candidate?.candidate||candidate||'').toLowerCase();const type=String(candidate?.type||'').toLowerCase();const relay=type==='relay'||/ typ relay /.test(raw);const address=String(candidate?.address||(raw.match(/candidate:\S+ \d+ \S+ \d+ ([^ ]+)/)||[])[1]||'').toLowerCase().replace(/^\[|\]$/g,'');const mdns=/\.local$/.test(address);const ipv4=/^(?:\d{1,3}\.){3}\d{1,3}$/.test(address);const ipv6=address.includes(':')&&/^[0-9a-f:]+$/.test(address);const privateIp=/^(10\.|192\.168\.|172\.(1[6-9]|2\d|3[01])\.|127\.|169\.254\.|::1$|f[cd][0-9a-f]{2}:|fe[89ab][0-9a-f]:)/i.test(address);return{address,relay,privateIp,publicIp:(ipv4||ipv6)&&!mdns&&!privateIp&&!relay}}
async function waitForIceGathering(pc,timeoutMs){if(pc.iceGatheringState==='complete')return true;return await new Promise(resolve=>{let settled=false;const finish=(value)=>{if(settled)return;settled=true;clearTimeout(timer);pc.removeEventListener('icegatheringstatechange',changed);resolve(value)};const changed=()=>{if(pc.iceGatheringState==='complete')finish(true)};const timer=setTimeout(()=>finish(false),timeoutMs);pc.addEventListener('icegatheringstatechange',changed)})}
async function probeWebRtc(){let pc;const pubs=new Set();let priv=false,relay=false;try{pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.cloudflare.com:3478'}]});pc.createDataChannel('route');pc.onicecandidate=(e)=>{if(!e.candidate)return;const candidate=classify(e.candidate);if(candidate.publicIp&&candidate.address)pubs.add(candidate.address);priv=priv||candidate.privateIp;relay=relay||candidate.relay};await pc.setLocalDescription(await pc.createOffer());const complete=await waitForIceGathering(pc,8000);const publicCandidates=[...pubs].slice(0,8);return{webrtc_public_candidate:publicCandidates.length>0,webrtc_public_candidates:publicCandidates,webrtc_private_candidate:priv,webrtc_relay_candidate:relay,webrtc_gathering_completed:complete,browser_probe_completed:complete}}catch{return{webrtc_public_candidate:false,webrtc_public_candidates:[],webrtc_private_candidate:false,webrtc_relay_candidate:false,webrtc_gathering_completed:false,browser_probe_completed:false}}finally{if(pc)pc.close()}}
async function probeNetwork(family){const local=/^(127\.0\.0\.1|localhost|\[::1\])$/.test(location.hostname);const endpoint=local?('/v1/network?family='+family):('https://'+(family==='ipv4'?'v4':'v6')+'.route-check.saturnws.com/v1/network');const headers={'Content-Type':'application/json','X-Route-Attempt':attempt,'X-Route-Token':token};if(local)headers['X-Saturn-QA-Loopback']='1';try{const response=await fetch(endpoint,{method:'POST',headers,body:'{}',cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer'});const data=await response.json();if(!response.ok||!data.success)throw new Error('network_probe_rejected');return data}catch{return null}}
async function waitDecision(){for(let i=0;i<40;i+=1){try{const response=await fetch('/v1/browser-result',{method:'POST',headers:{'Content-Type':'application/json','X-Route-Attempt':attempt,'X-Route-Token':token},body:'{}',cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer'});const data=await response.json();if(response.ok&&data.success&&data.decision)return data}catch{}await new Promise(resolve=>setTimeout(resolve,250))}return null}
async function acknowledgeDecision(){try{const response=await fetch('/v1/browser-ack',{method:'POST',headers:{'Content-Type':'application/json','X-Route-Attempt':attempt,'X-Route-Token':token},body:'{}',cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer'});return response.ok}catch{return false}}
async function runCheck(){try{const [ipv4,ipv6,observation]=await Promise.all([probeNetwork('ipv4'),probeNetwork('ipv6'),probeWebRtc()]);observation.ipv4_probe_attempted=true;observation.ipv6_probe_attempted=true;byId('ipv4').textContent=ipv4?c.measured:c.unavailable;byId('ipv6').textContent=ipv6?c.measured:c.unavailable;byId('dns').textContent=c.dnsLimited;const sidePath=observation.webrtc_private_candidate||observation.webrtc_public_candidate;byId('webrtc').textContent=observation.browser_probe_completed?(sidePath?c.sideDetected:c.noSide):c.unknown;const response=await fetch('/v1/observe',{method:'POST',headers:{'Content-Type':'application/json','X-Route-Attempt':attempt,'X-Route-Token':token},body:JSON.stringify(observation),cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer'});const data=await response.json();if(!response.ok||!data.success)throw new Error('probe_rejected');byId('https').textContent=c.connected;byId('exit').textContent=data.exit_ip||data.exit_ip_masked||ipv4?.exit_ip||ipv4?.exit_ip_masked||ipv6?.exit_ip||ipv6?.exit_ip_masked||c.unavailable;byId('title').textContent=c.measurementDone;byId('detail').textContent=c.verifying;const decision=await waitDecision();if(!decision)throw new Error('decision_unavailable');const qualified=decision.decision==='qualified';finish(qualified,qualified?c.successTitle:c.failureTitle,qualified?c.successDetail:c.failureDetail);if(!await acknowledgeDecision())finish(false,visualCopy.ackFailedTitle,c.ackFailed)}catch{byId('https').textContent=c.failed;for(const id of ['dns','ipv4','ipv6','webrtc'])byId(id).textContent=c.unknown;finish(false,c.failedTitle,c.failedDetail)}}
let started=false;window.__saturnStartRouteCheck=(input)=>{if(started||!input||input.attempt!==attempt||!/^[A-Za-z0-9_-]{32,64}$/.test(attempt)||typeof input.token!=='string'||input.token.length<32||input.token.length>256)return false;started=true;token=input.token;void runCheck();return true};setTimeout(()=>{if(!started)finish(false,c.invalidTitle,c.invalidDetail)},15000);
if(launchToken)window.__saturnStartRouteCheck({attempt,token:launchToken});
</script>
</body>
</html>`
