/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: 16a5e2272c5c90aab484fd19f3c82d59)
interface __BaseEnv_Env {
	INIT_RATE_LIMITER: RateLimit;
	QA_LOOPBACK_ALLOWED: "false";
	ROUTE_ATTEMPTS: DurableObjectNamespace<import("./index").RouteAttempt>;
	POLICY_CAPABILITIES: Service /* entrypoint RouteCapabilityService from saturnws-policy */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "RouteAttempt";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
