export const publicCopy = {
  en: {
    announcement: 'A clearer way to prepare and return to every account session',
    heroTitle: 'Run every account from one organized workspace.',
    heroBody: 'Saturn Workspace brings account records, prepared browser profiles, reminders, saved email, and recovery into one focused Windows workspace.',
    heroPrimary: 'Create your account',
    heroSecondary: 'See how it works',
    proofOne: 'Prepared browser profiles',
    proofTwo: 'Account context stays together',
    proofThree: 'Local and cloud recovery',
    coreTitle: 'The context you need before every session.',
    coreBody: 'Stop rebuilding the same setup from memory. Saturn keeps account details, browser choices, reminders, and recovery state close to the work they support.',
    sessionsTitle: 'Prepare a session in one deliberate flow.',
    sessionsBody: 'Choose the account, browser environment, destination, and connection settings. Saturn keeps the flow compact and remembers the context you need next time.',
    stepAccount: 'Choose an account',
    stepAccountBody: 'Use a saved email record or enter the account you need.',
    stepProfile: 'Prepare the profile',
    stepProfileBody: 'Open an isolated AdsPower profile with the settings saved for that account.',
    stepLaunch: 'Start with context',
    stepLaunchBody: 'Return to saved settings, reminders, and the account history without rebuilding the session.',
    accountsTitle: 'Accounts, reminders, and status in one view.',
    accountsBody: 'See what needs attention, reopen a prepared profile, and keep the latest account state visible without turning the workspace into a spreadsheet.',
    backupTitle: 'Recovery is visible before you need it.',
    backupBody: 'Keep local backup state and Google Drive recovery paths understandable, with clear restore points and saved email records alongside the accounts they support.',
    isolationTitle: 'Prepared browser environments reduce accidental overlap.',
    isolationBody: 'Saturn keeps prepared AdsPower profile settings attached to the account workflow, so each session starts from the right context.',
    proxyTitle: 'Fast proxy selection inside the same workflow.',
    proxyBody: 'Choose country, protocol, stability, and an optional IP prefix from one place. Saturn prepares a fast usable proxy before launch when the session needs one.',
    providers: 'Proxy options',
    useCasesTitle: 'A workspace that reflects the real work.',
    useCasesBody: 'Move between session preparation, account follow-up, saved email, and recovery without losing where each item belongs.',
    pricingTitle: 'Saturn Workspace plans',
    pricingBody: 'Every current plan includes the same Saturn Workspace features. The difference is subscription period, price, and free-trial terms.',
    weeklyName: 'Weekly plan',
    weeklyBody: 'Renews weekly.',
    monthlyName: 'Monthly plan',
    monthlyBody: 'Renews monthly.',
    annualName: 'Annual plan',
    annualBody: 'Renews yearly.',
    weeklyOriginalPrice: '$15',
    weeklyPrice: '$10',
    monthlyOriginalPrice: '$50',
    monthlyPrice: '$35',
    annualOriginalPrice: '$600',
    annualPrice: '$350',
    weeklyPeriod: '/week',
    monthlyPeriod: '/month',
    annualPeriod: '/year',
    requestAccess: 'Subscribe',
    contactUs: 'Contact us',
    recommended: 'Popular',
    featureWorkspace: 'Full Saturn Workspace features',
    featureProfiles: 'Prepared account and browser workflows',
    featureRecovery: 'Backup and recovery tools',
    featureUpdates: 'Managed product updates',
    trialPromo: 'Monthly and annual plans include 7 free trial days.',
    compareTitle: 'Included with every plan',
    trustNote: 'Checkout is not available right now. You can still create an account and review the plans.',
    faqTitle: 'Questions before you begin',
    faqWindows: 'Does Saturn Workspace run on Windows?',
    faqWindowsBody: 'Yes. The desktop workspace is prepared for supported Windows environments.',
    faqProfiles: 'Does Saturn create browser profiles?',
    faqProfilesBody: 'Saturn can prepare AdsPower profiles and browser sessions using the settings saved with the account workflow.',
    faqBackup: 'Can I recover saved account data?',
    faqBackupBody: 'The workspace presents local backup and Google Drive recovery states so available restore points remain visible.',
    faqProxy: 'Do I need proxy configuration?',
    faqProxyBody: 'No. Proxy configuration is optional and supports sessions that require it.',
    finalTitle: 'Make the next session easier to start.',
    finalBody: 'Create your Saturn Workspace account and keep the operational context for every account in one place.',
    productPageTitle: 'Built around repeatable account sessions.',
    productPageBody: 'See how account organization, prepared profiles, saved email, reminders, and recovery work as one connected workspace.',
    downloadNatural: 'Release information will appear here when a Windows build is available for your account.',
    releaseNatural: 'Release notes and channel information will appear here when available.',
    contactBody: 'Choose the topic that matches your request.',
    legalBody: 'This document will present the approved policy text for Saturn Workspace.',
    messageSent: 'Your message was sent.',
    signInEyebrow: 'Saturn Workspace account',
    signInTitle: 'Welcome back',
    signInBody: 'Sign in to continue.',
  },
  ar: {
    announcement: 'طريقة أوضح لتجهيز جلسات الحسابات والعودة إليها',
    heroTitle: 'أدِر كل حساب من مساحة عمل واحدة منظمة.',
    heroBody: 'يجمع Saturn Workspace بيانات الحسابات وملفات المتصفح المجهزة والتذكيرات والبريد المحفوظ والاستعادة داخل مساحة عمل واحدة لويندوز.',
    heroPrimary: 'إنشاء حساب',
    heroSecondary: 'اكتشف طريقة العمل',
    proofOne: 'ملفات متصفح مجهزة',
    proofTwo: 'سياق الحساب محفوظ معًا',
    proofThree: 'استعادة محلية وسحابية',
    coreTitle: 'كل ما تحتاجه قبل بدء أي جلسة.',
    coreBody: 'لا تعد تجهيز الإعدادات نفسها من الذاكرة. يحتفظ Saturn ببيانات الحساب وخيارات المتصفح والتذكيرات وحالة الاستعادة قرب العمل المرتبط بها.',
    sessionsTitle: 'جهّز الجلسة ضمن خطوات واضحة ومترابطة.',
    sessionsBody: 'اختر الحساب وبيئة المتصفح والوجهة وإعدادات الاتصال. يحافظ Saturn على بساطة الخطوات ويتذكر السياق الذي ستحتاجه لاحقًا.',
    stepAccount: 'اختر الحساب',
    stepAccountBody: 'استخدم بريدًا محفوظًا أو أدخل الحساب المطلوب.',
    stepProfile: 'جهّز البروفايل',
    stepProfileBody: 'افتح بروفايل AdsPower منفصلًا بالإعدادات المحفوظة لهذا الحساب.',
    stepLaunch: 'ابدأ بالسياق الكامل',
    stepLaunchBody: 'ارجع إلى الإعدادات والتذكيرات وسجل الحساب دون إعادة بناء الجلسة.',
    accountsTitle: 'الحسابات والتذكيرات والحالة في مكان واحد.',
    accountsBody: 'اعرف ما يحتاج للمراجعة، وأعد فتح البروفايل المجهز، واحتفظ بآخر حالة للحساب أمامك دون تحويل مساحة العمل إلى جدول معقد.',
    backupTitle: 'اجعل الاستعادة واضحة قبل أن تحتاجها.',
    backupBody: 'تابع حالة النسخ المحلي ومسارات الاستعادة من Google Drive، مع نقاط استعادة واضحة وبريد محفوظ بجانب الحسابات المرتبطة به.',
    isolationTitle: 'بيئات المتصفح المجهزة تقلل تداخل الجلسات بالخطأ.',
    isolationBody: 'يحافظ Saturn على إعدادات بروفايلات AdsPower المجهزة مرتبطة بسير عمل الحساب، حتى تبدأ كل جلسة من سياقها الصحيح.',
    proxyTitle: 'اختيار بروكسي سريع من داخل سير العمل نفسه.',
    proxyBody: 'اختر الدولة والبروتوكول ومدة الثبات وبادئة IP الاختيارية من مكان واحد. تجهّز الأداة بروكسيًا سريعًا صالحًا قبل فتح الجلسة عندما تحتاجه.',
    providers: 'خيارات البروكسي',
    useCasesTitle: 'مساحة عمل تعكس الاستخدام الفعلي.',
    useCasesBody: 'انتقل بين تجهيز الجلسة ومتابعة الحساب والبريد المحفوظ والاستعادة دون فقدان مكان كل عنصر.',
    pricingTitle: 'خطط اشتراك Saturn Workspace',
    pricingBody: 'جميع الخطط الحالية تشمل نفس ميزات Saturn Workspace. الاختلاف في مدة الاشتراك والسعر وشروط التجربة المجانية.',
    weeklyName: 'الخطة الأسبوعية',
    weeklyBody: 'تجدد أسبوعيًا.',
    monthlyName: 'الخطة الشهرية',
    monthlyBody: 'تجدد شهريًا.',
    annualName: 'الخطة السنوية',
    annualBody: 'تجدد سنويًا.',
    weeklyOriginalPrice: '$15',
    weeklyPrice: '$10',
    monthlyOriginalPrice: '$50',
    monthlyPrice: '$35',
    annualOriginalPrice: '$600',
    annualPrice: '$350',
    weeklyPeriod: '/أسبوع',
    monthlyPeriod: '/شهر',
    annualPeriod: '/سنة',
    requestAccess: 'اشترك',
    contactUs: 'تواصل معنا',
    recommended: 'رائج',
    featureWorkspace: 'كامل ميزات Saturn Workspace',
    featureProfiles: 'تجهيز الحسابات وبيئات المتصفح',
    featureRecovery: 'أدوات النسخ والاستعادة',
    featureUpdates: 'تحديثات المنتج المُدارة',
    trialPromo: 'الخطتان الشهرية والسنوية تشملان 7 أيام تجربة مجانية.',
    compareTitle: 'مشمول في كل خطة',
    trustNote: 'الدفع غير متاح حاليًا. يمكنك إنشاء حساب ومراجعة الخطط.',
    faqTitle: 'أسئلة قبل البدء',
    faqWindows: 'هل يعمل Saturn Workspace على ويندوز؟',
    faqWindowsBody: 'نعم. مساحة العمل المكتبية مجهزة لبيئات ويندوز المدعومة.',
    faqProfiles: 'هل ينشئ Saturn بروفايلات متصفح؟',
    faqProfilesBody: 'يستطيع Saturn تجهيز بروفايلات AdsPower وجلسات المتصفح باستخدام الإعدادات المحفوظة مع الحساب.',
    faqBackup: 'هل يمكن استعادة بيانات الحسابات المحفوظة؟',
    faqBackupBody: 'تعرض مساحة العمل حالات النسخ المحلي والاستعادة من Google Drive حتى تظل نقاط الاستعادة المتاحة واضحة.',
    faqProxy: 'هل أحتاج إلى إعداد بروكسي؟',
    faqProxyBody: 'لا. إعداد البروكسي اختياري ويدعم فقط الجلسات التي تحتاجه.',
    finalTitle: 'اجعل بدء الجلسة التالية أسهل.',
    finalBody: 'أنشئ حساب Saturn Workspace واحتفظ بسياق كل حساب في مكان واحد.',
    productPageTitle: 'مصمم حول جلسات الحسابات المتكررة.',
    productPageBody: 'شاهد كيف تعمل الحسابات والبروفايلات المجهزة والبريد والتذكيرات والاستعادة كمساحة عمل واحدة.',
    downloadNatural: 'ستظهر معلومات الإصدار هنا عند توفر نسخة ويندوز لحسابك.',
    releaseNatural: 'ستظهر ملاحظات الإصدار والقناة هنا عند توفرها.',
    contactBody: 'اختر الموضوع المناسب لطلبك.',
    legalBody: 'ستعرض هذه الصفحة نص السياسة المعتمد لخدمة Saturn Workspace.',
    messageSent: 'تم إرسال رسالتك.',
    signInEyebrow: 'حساب Saturn Workspace',
    signInTitle: 'مرحبًا بعودتك',
    signInBody: 'سجّل الدخول للمتابعة.',
  },
} as const
